### ISSUE TITLE
Script Error: attempt to compare nil with number

### ISSUE THREAD

**Issue by chiefblck** [qbcore-framework/qb-vehiclesales#25]
Everytime i try to put my own vehicle on sales or just sell it the resource sends this in the console.
![image](https://user-images.githubusercontent.com/58475623/148295707-47003012-3640-4f49-aa9d-87e70edd4743.png)

**Comment by Mazvis1** [comment]
Same error for me

**Comment by b1uedr4gon** [comment]
Same problem here

**Comment by WEEZOOKARP** [comment]
just put up a pull request that fixes this error
#35 
I'd suggest you look into it

**Comment by HeadSh0** [comment]
Has anyone got the fix yet

**Comment by HeadSh0** [comment]
having same problem

**Comment by ericb160** [comment]
same :(

**Comment by Hadgebury** [comment]
Having same issue recently and haven't touched this script since it was last working

**Comment by Hadgebury** [comment]
> Having same issue recently and haven't touched this script since it was last working

Fixed My Issue. Was Caused By qb-garages mixing this external call at bottom of the script:

--Call from qb-vehiclesales
`QBCore.Functions.CreateCallback("qb-garage:server:checkVehicleOwner", function(source, cb, plate)
    local src = source
    local pData = QBCore.Functions.GetPlayer(src)
    MySQL.Async.fetchAll('SELECT * FROM player_vehicles WHERE plate = ? AND citizenid = ?',{plate, pData.PlayerData.citizenid}, function(result)
        if result[1] then
            cb(true, result[1].balance)
        else
            cb(false)
        end
    end)
end)`

**Comment by Hadgebury** [comment]
@b1uedr4gon @Mazvis1 @ericb160 @chiefblck @HeadSh0 

I Had The Same Issue. Was Caused By qb-garages (Problem Started When I Changed From The Default Garage Script To An Edited Version)

The Fix That Worked For Me Was Adding These Two Missing Parts In The main.lua Within The Server Folder Of qb-garages.

![image](https://user-images.githubusercontent.com/34612010/159798286-9e5ce2dc-76b2-4c92-a3a9-ff4d643d5eee.png)


![image](https://user-images.githubusercontent.com/34612010/159798334-2e4b9bbe-63c1-43d5-a356-88d83b824f4b.png)

**Comment by Hadgebury** [comment]
The First Image Is To Show That Only The HIGHLIGHTED Part Was Needed To Be Added As It Was Missing

**Comment by Hadgebury** [comment]
@b1uedr4gon @Mazvis1 @ericb160 @chiefblck @HeadSh0 

Issue Was Caused On My Server Was That We WereUsing An Edited/Different Version Of qb-garages than what originally came with qb-core install.

The Fix Was Just To Add This To The Bottom Of qb-garages (Or Whatever Garage Script Your Using) main.lua File In The Server Folder.

![image](https://user-images.githubusercontent.com/34612010/159800296-91513138-5b49-4ef4-a47c-704d0815ced9.png)

**Comment by TapFreee** [comment]
can send the it in here

**Comment by TapFreee** [comment]
@Hadgebury

**Comment by Fistsofury** [comment]
> @Hadgebury

--Call from qb-vehiclesales
QBCore.Functions.CreateCallback("qb-garage:server:checkVehicleOwner", function(source, cb, plate)
    local src = source
    local pData = QBCore.Functions.GetPlayer(src)
    MySQL.Async.fetchAll('SELECT * FROM player_vehicles WHERE plate = ? AND citizenid = ?',{plate, pData.PlayerData.citizenid}, function(result)
        if result[1] then
            cb(true, result[1].balance)
        else
            cb(false)
        end
    end)
end)
